"""Type stub for Pubkey exposed by ``solana_kit._core``.

Mirrors ``src/_native/src/pubkey.rs``.
"""

from __future__ import annotations

class Pubkey:
    """32-byte Solana account address."""

    PUBKEY_BYTES: int  # 32
    data: bytes

    @staticmethod
    def from_string(s: str) -> Pubkey: ...
    @staticmethod
    def from_bytes(data: bytes) -> Pubkey: ...
    @staticmethod
    def new_rand() -> Pubkey: ...
    def to_string(self) -> str: ...
    def is_on_curve(self) -> bool: ...
    def __bytes__(self) -> bytes: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
