"""Type stub for Hash exposed by ``solana_kit._core``."""

from __future__ import annotations

class Hash:
    """32-byte hash (blockhash / lifetime specifier)."""

    HASH_BYTES: int  # 32
    data: bytes

    def __init__(self, data: bytes) -> None: ...
    @staticmethod
    def from_bytes(data: bytes) -> Hash: ...
    @staticmethod
    def new_unique() -> Hash: ...
    def to_bytes(self) -> bytes: ...
    def __bytes__(self) -> bytes: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
