"""Type stubs for the Keypair class exposed by ``solana_kit._core``.

The class is defined in the native ``_core`` extension module (single
``.so``); this file exists only to keep the stub layer split by domain.
"""

from __future__ import annotations

from ._core_pubkey import Pubkey, Signature

class Keypair:
    """Ed25519 keypair — generate, sign, verify, import/export."""

    SECRET_KEY_LENGTH: int  # 32
    KEYPAIR_LENGTH: int  # 64

    @staticmethod
    def generate() -> Keypair: ...
    @staticmethod
    def from_bytes(data: bytes) -> Keypair: ...
    @staticmethod
    def from_base58_string(s: str) -> Keypair: ...
    @staticmethod
    def from_seed(seed: bytes) -> Keypair: ...
    def pubkey(self) -> Pubkey: ...
    def sign(self, message: bytes) -> Signature: ...
    @staticmethod
    def verify(message: bytes, signature: Signature, pubkey: Pubkey) -> bool: ...
    def to_base58_string(self) -> str: ...
    @property
    def secret_bytes(self) -> bytes: ...
    def clone(self) -> Keypair: ...
    def __bytes__(self) -> bytes: ...
    def __repr__(self) -> str: ...
